name: Build
description: Sets up the build environment.
runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10.4.1
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - name: Install dependencies
      shell: bash
      run: pnpm --filter=backend install
