name: Anti-Grindr CI

on:
  push:
    branches:
      - main
      - ci-cd

jobs:
  unit-test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-backend
      - name: Run unit tests
        run: pnpm --filter=backend run test:unit
  integration-test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-backend
      - name: Run integration tests
        run: pnpm --filter=backend run test:int
    